### ISSUE TITLE
Bug: Fix `empresa.html` dynamic content

### ISSUE THREAD

**Issue by claudiovallejo** [materialesvallejo/sitio#6]
## Issue
`empresa.html` displays open content (last paragraph and contact details) during lunch hours.

## Source
`site.js.erb` in lines 219 - 232.

**Comment by materialesvallejo** [comment]
## Fix
Fixed line 166 from `site.js.erb` inside `updateDynamicContent(officeStatus, dayType)`.

```
if (currentPath.includes('empresa')) {
  aboutContent("Lunch");
}
```
